### ISSUE TITLE
Consider adding a license & making a release

### ISSUE THREAD

**Issue by turion** [flupe/generics#5]
Hi :) I'm currently trying to package this library for https://github.com/NixOS/nixpkgs/. See https://github.com/NixOS/nixpkgs/pull/153757/.

I can't really merge it yet because I don't know the license of your project. What open source license do you want to add?

Also, if you can make a release with a version tag, that's highly appreciated. (But not strictly necessary right now.)

**Comment by flupe** [comment]
Hello @turion, thank you for trying to package the library!

The most recent version of the library is in the `accessibility` branch, but as you have noted I have yet to do a proper release, document everything and clean up the rough edges.

I haven't thought about it but will most likely license the lib under MIT. You can proceed with this license if it's urgent. If you can afford to wait a few days I can try to make a first release this week end.

For further documentation, I will need some more time thought and cannot make any promises.

**Comment by turion** [comment]
Thanks for your quick reply :) it was very easy to package, it turns out.

There is no hurry, so I'll wait for the release and then update my PR.

**Comment by turion** [comment]
This seems to be done in https://github.com/flupe/generics/releases/tag/v1.0.0 Thanks!
